export interface InventorySeedItem {
  sizeId: number;
  stockId: string;
  oldItemId: string;
  itemName: string;
  openingQuantity: number;
  unit: string;
  minimumStock: number;
}

export const INVENTORY_SEED: InventorySeedItem[] = [
  {
    sizeId: 1,
    stockId: "R58-S-0001",
    oldItemId: "R58-PB-001",
    itemName: "Union UPVC 1\"",
    openingQuantity: 9,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 2,
    stockId: "R58-S-0002",
    oldItemId: "R58-PB-002",
    itemName: "Union UPVC 1½\"",
    openingQuantity: 6,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 3,
    stockId: "R58-S-0003",
    oldItemId: "R58-PB-003",
    itemName: "Union UPVC 2\"",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 4,
    stockId: "R58-S-0004",
    oldItemId: "R58-PB-004",
    itemName: "Union CPVC 1\"",
    openingQuantity: 15,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 5,
    stockId: "R58-S-0005",
    oldItemId: "R58-PB-005",
    itemName: "Union CPVC 1¼\"",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 6,
    stockId: "R58-S-0006",
    oldItemId: "R58-PB-006",
    itemName: "Union CPVC 1½\"",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 7,
    stockId: "R58-S-0007",
    oldItemId: "R58-PB-007",
    itemName: "Nipple GI ½\"X4\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 8,
    stockId: "R58-S-0008",
    oldItemId: "R58-PB-008",
    itemName: "Nipple GI ½\"X6\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 9,
    stockId: "R58-S-0009",
    oldItemId: "R58-PB-009",
    itemName: "Nipple GI 1½\"X6\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 10,
    stockId: "R58-S-0010",
    oldItemId: "R58-PB-010",
    itemName: "Nipple GI ¾\"X4\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 11,
    stockId: "R58-S-0011",
    oldItemId: "R58-PB-011",
    itemName: "Nipple GI ¾\"X6\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 12,
    stockId: "R58-S-0012",
    oldItemId: "R58-PB-012",
    itemName: "Nipple GI 1¼\"X4\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 13,
    stockId: "R58-S-0013",
    oldItemId: "R58-PB-013",
    itemName: "Nipple GI 1¼\"X9\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 14,
    stockId: "R58-S-0014",
    oldItemId: "R58-PB-014",
    itemName: "Ball Valve ½\" GI DRP",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 15,
    stockId: "R58-S-0015",
    oldItemId: "R58-PB-015",
    itemName: "Ball Valve 1½\" GI DRP",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 16,
    stockId: "R58-S-0016",
    oldItemId: "R58-PB-016",
    itemName: "Ball Valve ¾\" GI DRP",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 17,
    stockId: "R58-S-0017",
    oldItemId: "R58-PB-017",
    itemName: "M-Seal 250gm pair",
    openingQuantity: 3,
    unit: "Pair",
    minimumStock: 0,
  },
  {
    sizeId: 18,
    stockId: "R58-S-0018",
    oldItemId: "R58-PB-018",
    itemName: "Teflon Tape ½\"",
    openingQuantity: 86,
    unit: "Roll",
    minimumStock: 0,
  },
  {
    sizeId: 19,
    stockId: "R58-S-0019",
    oldItemId: "R58-PB-019",
    itemName: "Tee UPVC 1\"",
    openingQuantity: 9,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 20,
    stockId: "R58-S-0020",
    oldItemId: "R58-PB-020",
    itemName: "Tee UPVC 1½\"",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 21,
    stockId: "R58-S-0021",
    oldItemId: "R58-PB-021",
    itemName: "Tee UPVC 1½\"X2\" with Bush",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 22,
    stockId: "R58-S-0022",
    oldItemId: "R58-PB-022",
    itemName: "Tee CPVC 1½\"",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 23,
    stockId: "R58-S-0023",
    oldItemId: "R58-PB-023",
    itemName: "Solvent CPVC 237ml",
    openingQuantity: 5,
    unit: "Bottle",
    minimumStock: 0,
  },
  {
    sizeId: 24,
    stockId: "R58-S-0024",
    oldItemId: "R58-PB-024",
    itemName: "Solvent CPVC 500ml",
    openingQuantity: 0,
    unit: "Bottle",
    minimumStock: 0,
  },
  {
    sizeId: 25,
    stockId: "R58-S-0025",
    oldItemId: "R58-PB-025",
    itemName: "Solvent PVC 100ml",
    openingQuantity: 3,
    unit: "Bottle",
    minimumStock: 0,
  },
  {
    sizeId: 26,
    stockId: "R58-S-0026",
    oldItemId: "R58-PB-026",
    itemName: "Solvent PVC 500ml",
    openingQuantity: 0,
    unit: "Bottle",
    minimumStock: 0,
  },
  {
    sizeId: 27,
    stockId: "R58-S-0027",
    oldItemId: "R58-PB-027",
    itemName: "Solvent UPVC 237ml",
    openingQuantity: 3,
    unit: "Bottle",
    minimumStock: 0,
  },
  {
    sizeId: 28,
    stockId: "R58-S-0028",
    oldItemId: "R58-PB-028",
    itemName: "Socket CPVC ¾\"",
    openingQuantity: 3,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 29,
    stockId: "R58-S-0029",
    oldItemId: "R58-PB-029",
    itemName: "Socket CPVC 1\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 30,
    stockId: "R58-S-0030",
    oldItemId: "R58-PB-030",
    itemName: "Socket CPVC 1¼\"",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 31,
    stockId: "R58-S-0031",
    oldItemId: "R58-PB-031",
    itemName: "Push Tooti PVC",
    openingQuantity: 19,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 32,
    stockId: "R58-S-0032",
    oldItemId: "R58-PB-032",
    itemName: "FTA UPVC 1\"X1\" Brass",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 33,
    stockId: "R58-S-0033",
    oldItemId: "R58-PB-033",
    itemName: "FTA UPVC 1½\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 34,
    stockId: "R58-S-0034",
    oldItemId: "R58-PB-034",
    itemName: "FTA UPVC 2\"X2\" Brass",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 35,
    stockId: "R58-S-0035",
    oldItemId: "R58-PB-035",
    itemName: "FTA CPVC ¾\"X¾\" Brass",
    openingQuantity: 10,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 36,
    stockId: "R58-S-0036",
    oldItemId: "R58-PB-036",
    itemName: "FTA CPVC 1\"X1\" Brass",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 37,
    stockId: "R58-S-0037",
    oldItemId: "R58-PB-037",
    itemName: "FTA CPVC 1¼\"X1¼\" Brass",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 38,
    stockId: "R58-S-0038",
    oldItemId: "R58-PB-038",
    itemName: "FTA CPVC 1½\"X1½\" Brass",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 39,
    stockId: "R58-S-0039",
    oldItemId: "R58-PB-039",
    itemName: "Endcap UPVC 1½\"",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 40,
    stockId: "R58-S-0040",
    oldItemId: "R58-PB-040",
    itemName: "Elbow UPVC ¾\"",
    openingQuantity: 3,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 41,
    stockId: "R58-S-0041",
    oldItemId: "R58-PB-041",
    itemName: "Elbow UPVC 1\"",
    openingQuantity: 6,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 42,
    stockId: "R58-S-0042",
    oldItemId: "R58-PB-042",
    itemName: "Elbow UPVC 1½\"",
    openingQuantity: 6,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 43,
    stockId: "R58-S-0043",
    oldItemId: "R58-PB-043",
    itemName: "Elbow UPVC 1*1¾\" with bush",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 44,
    stockId: "R58-S-0044",
    oldItemId: "R58-PB-044",
    itemName: "Elbow UPVC 2\"",
    openingQuantity: 3,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 45,
    stockId: "R58-S-0045",
    oldItemId: "R58-PB-045",
    itemName: "Elbow CPVC ¾\"",
    openingQuantity: 7,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 46,
    stockId: "R58-S-0046",
    oldItemId: "R58-PB-046",
    itemName: "Elbow CPVC 1\"",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 47,
    stockId: "R58-S-0047",
    oldItemId: "R58-PB-047",
    itemName: "Elbow CPVC 1¼\"",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 48,
    stockId: "R58-S-0048",
    oldItemId: "R58-PB-048",
    itemName: "Clamp GI 3\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 49,
    stockId: "R58-S-0049",
    oldItemId: "R58-PB-049",
    itemName: "Clamp GI 4\"",
    openingQuantity: 11,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 50,
    stockId: "R58-S-0050",
    oldItemId: "R58-PB-050",
    itemName: "Ball Valve ¾\" CPVC",
    openingQuantity: 8,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 51,
    stockId: "R58-S-0051",
    oldItemId: "R58-PB-051",
    itemName: "Ball Valve 1\" CPVC",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 52,
    stockId: "R58-S-0052",
    oldItemId: "R58-PB-052",
    itemName: "Ball Valve 1½\" CPVC",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 53,
    stockId: "R58-S-0053",
    oldItemId: "R58-PB-053",
    itemName: "MTA UPVC 1\"x1\" Brass",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 54,
    stockId: "R58-S-0054",
    oldItemId: "R58-PB-054",
    itemName: "MTA UPVC 1½\" Brass",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 55,
    stockId: "R58-S-0055",
    oldItemId: "R58-PB-055",
    itemName: "MTA UPVC 2\"x2\" Brass",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 56,
    stockId: "R58-S-0056",
    oldItemId: "R58-PB-056",
    itemName: "Socket UPVC ¾\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 57,
    stockId: "R58-S-0057",
    oldItemId: "R58-PB-057",
    itemName: "Socket UPVC 1\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 58,
    stockId: "R58-S-0058",
    oldItemId: "R58-PB-058",
    itemName: "Socket UPVC 1½\"",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 59,
    stockId: "R58-S-0059",
    oldItemId: "R58-PB-059",
    itemName: "Socket UPVC 1½\"X1¼\" with Bush",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 60,
    stockId: "R58-S-0060",
    oldItemId: "R58-PB-060",
    itemName: "Socket UPVC 2\"",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 61,
    stockId: "R58-S-0061",
    oldItemId: "R58-PB-061",
    itemName: "MTA CPVC ¾\"x¾\" Brass",
    openingQuantity: 10,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 62,
    stockId: "R58-S-0062",
    oldItemId: "R58-PB-062",
    itemName: "MTA CPVC 1\"x1\" Brass",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 63,
    stockId: "R58-S-0063",
    oldItemId: "R58-PB-063",
    itemName: "MTA CPVC 1¼\"x1¼\" Brass",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 64,
    stockId: "R58-S-0064",
    oldItemId: "R58-PB-064",
    itemName: "MTA CPVC 1½\"x1½\" Brass",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 65,
    stockId: "R58-S-0065",
    oldItemId: "R58-PB-065",
    itemName: "Phase Half Round Brass ½\"",
    openingQuantity: 16,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 66,
    stockId: "R58-S-0066",
    oldItemId: "R58-PB-066",
    itemName: "Phase No.-2 Brass ½\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 67,
    stockId: "R58-S-0067",
    oldItemId: "R58-PB-067",
    itemName: "Phase No.-3 Brass ½\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 68,
    stockId: "R58-S-0068",
    oldItemId: "R58-PB-068",
    itemName: "Phase No.-5 Brass ½\"",
    openingQuantity: 13,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 69,
    stockId: "R58-S-0069",
    oldItemId: "R58-PB-069",
    itemName: "Hexa Blade Double",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 70,
    stockId: "R58-S-0070",
    oldItemId: "R58-PB-070",
    itemName: "Hexa Blade Single",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 71,
    stockId: "R58-S-0071",
    oldItemId: "R58-PB-071",
    itemName: "R-Socket CPVC 1\"X¾\"",
    openingQuantity: 3,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 72,
    stockId: "R58-S-0072",
    oldItemId: "R58-PB-072",
    itemName: "R-Socket CPVC 1¼\"X1\"",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 73,
    stockId: "R58-S-0073",
    oldItemId: "R58-PB-073",
    itemName: "R-Socket GI 1\"X¾\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 74,
    stockId: "R58-S-0074",
    oldItemId: "R58-PB-074",
    itemName: "R-Socket GI 2\"X1½\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 75,
    stockId: "R58-S-0075",
    oldItemId: "R58-PB-075",
    itemName: "R-Socket GI 1½\"X1¼\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 76,
    stockId: "R58-S-0076",
    oldItemId: "R58-PB-076",
    itemName: "R-Socket UPVC 1\"X¾\"",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 77,
    stockId: "R58-S-0077",
    oldItemId: "R58-EL-001",
    itemName: "MCB 16A SP",
    openingQuantity: 12,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 78,
    stockId: "R58-S-0078",
    oldItemId: "R58-EL-002",
    itemName: "MCB 32A Modular",
    openingQuantity: 6,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 79,
    stockId: "R58-S-0079",
    oldItemId: "R58-EL-003",
    itemName: "MCB 32A SP",
    openingQuantity: 12,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 80,
    stockId: "R58-S-0080",
    oldItemId: "R58-EL-004",
    itemName: "MCB 63A, 02P",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 81,
    stockId: "R58-S-0081",
    oldItemId: "R58-EL-005",
    itemName: "MCB 63A, 03P",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 82,
    stockId: "R58-S-0082",
    oldItemId: "R58-EL-006",
    itemName: "MCB DB 12way",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 83,
    stockId: "R58-S-0083",
    oldItemId: "R58-EL-007",
    itemName: "MCB DB 20way",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 84,
    stockId: "R58-S-0084",
    oldItemId: "R58-EL-008",
    itemName: "Top 3 Pin 16A",
    openingQuantity: 10,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 85,
    stockId: "R58-S-0085",
    oldItemId: "R58-EL-009",
    itemName: "Top 3 Pin 6A",
    openingQuantity: 3,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 86,
    stockId: "R58-S-0086",
    oldItemId: "R58-EL-010",
    itemName: "Junction Box MS 1\" (Concealed)",
    openingQuantity: 30,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 87,
    stockId: "R58-S-0087",
    oldItemId: "R58-EL-011",
    itemName: "Junction Box MS 8X6 (Concealed)",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 88,
    stockId: "R58-S-0088",
    oldItemId: "R58-EL-012",
    itemName: "Junction Box MS 9X3 (Concealed)",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 89,
    stockId: "R58-S-0089",
    oldItemId: "R58-EL-013",
    itemName: "Gitti",
    openingQuantity: 10,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 90,
    stockId: "R58-S-0090",
    oldItemId: "R58-EL-014",
    itemName: "Clip 04mm",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 91,
    stockId: "R58-S-0091",
    oldItemId: "R58-EL-015",
    itemName: "Clip 06mm",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 92,
    stockId: "R58-S-0092",
    oldItemId: "R58-EL-016",
    itemName: "Clip 08mm",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 93,
    stockId: "R58-S-0093",
    oldItemId: "R58-EL-017",
    itemName: "Clip 10mm",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 94,
    stockId: "R58-S-0094",
    oldItemId: "R58-EL-018",
    itemName: "Screw Black 1.5\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 95,
    stockId: "R58-S-0095",
    oldItemId: "R58-EL-019",
    itemName: "Screw Black 2\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 96,
    stockId: "R58-S-0096",
    oldItemId: "R58-EL-020",
    itemName: "Screw Brass 1.5\"",
    openingQuantity: 25,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 97,
    stockId: "R58-S-0097",
    oldItemId: "R58-EL-021",
    itemName: "Screw Brass 2\"",
    openingQuantity: 24,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 98,
    stockId: "R58-S-0098",
    oldItemId: "R58-EL-022",
    itemName: "Screw Brass 3\"",
    openingQuantity: 24,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 99,
    stockId: "R58-S-0099",
    oldItemId: "R58-EL-023",
    itemName: "Washer Brass Cup",
    openingQuantity: 10,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 100,
    stockId: "R58-S-0100",
    oldItemId: "R58-EL-024",
    itemName: "Cable Tie 150mm",
    openingQuantity: 11,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 101,
    stockId: "R58-S-0101",
    oldItemId: "R58-EL-025",
    itemName: "Cable Tie 200mm",
    openingQuantity: 9,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 102,
    stockId: "R58-S-0102",
    oldItemId: "R58-EL-026",
    itemName: "Acrylic Sheet",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 103,
    stockId: "R58-S-0103",
    oldItemId: "R58-EL-027",
    itemName: "Mica Sheet 10\"X5\"",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 104,
    stockId: "R58-S-0104",
    oldItemId: "R58-EL-028",
    itemName: "Mica Sheet 5\"X5\"",
    openingQuantity: 12,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 105,
    stockId: "R58-S-0105",
    oldItemId: "R58-EL-029",
    itemName: "Mica Sheet 8\"X5\"",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 106,
    stockId: "R58-S-0106",
    oldItemId: "R58-EL-030",
    itemName: "Mica Sheet 9\"X11\"",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 107,
    stockId: "R58-S-0107",
    oldItemId: "R58-EL-031",
    itemName: "Round Fan Sheet",
    openingQuantity: 12,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 108,
    stockId: "R58-S-0108",
    oldItemId: "R58-EL-032",
    itemName: "Round Sheet PVC",
    openingQuantity: 40,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 109,
    stockId: "R58-S-0109",
    oldItemId: "R58-EL-033",
    itemName: "Halogen 400W",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 110,
    stockId: "R58-S-0110",
    oldItemId: "R58-EL-034",
    itemName: "Cap 04mfd",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 111,
    stockId: "R58-S-0111",
    oldItemId: "R58-EL-035",
    itemName: "Cap 10mfd",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 112,
    stockId: "R58-S-0112",
    oldItemId: "R58-EL-036",
    itemName: "Cap 3.15mfd",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 113,
    stockId: "R58-S-0113",
    oldItemId: "R58-EL-037",
    itemName: "Cap 36mfd",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 114,
    stockId: "R58-S-0114",
    oldItemId: "R58-EL-038",
    itemName: "Cap 36mfd (pin)",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 115,
    stockId: "R58-S-0115",
    oldItemId: "R58-EL-039",
    itemName: "Cap 80-100mfd",
    openingQuantity: 3,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 116,
    stockId: "R58-S-0116",
    oldItemId: "R58-EL-040",
    itemName: "LED Bulb 09w",
    openingQuantity: 72,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 117,
    stockId: "R58-S-0117",
    oldItemId: "R58-EL-041",
    itemName: "LED Bulb 15w",
    openingQuantity: 26,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 118,
    stockId: "R58-S-0118",
    oldItemId: "R58-EL-042",
    itemName: "LED Bulb 15w_Churiwala",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 119,
    stockId: "R58-S-0119",
    oldItemId: "R58-EL-043",
    itemName: "LED Chip 100W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 120,
    stockId: "R58-S-0120",
    oldItemId: "R58-EL-044",
    itemName: "LED Chip 25W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 121,
    stockId: "R58-S-0121",
    oldItemId: "R58-EL-045",
    itemName: "LED Chip 30W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 122,
    stockId: "R58-S-0122",
    oldItemId: "R58-EL-046",
    itemName: "LED Chip 48W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 123,
    stockId: "R58-S-0123",
    oldItemId: "R58-EL-047",
    itemName: "LED Cob Light 18W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 124,
    stockId: "R58-S-0124",
    oldItemId: "R58-EL-048",
    itemName: "LED Driver",
    openingQuantity: 11,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 125,
    stockId: "R58-S-0125",
    oldItemId: "R58-EL-049",
    itemName: "Socket 6A And 16A (Universal Socket)",
    openingQuantity: 13,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 126,
    stockId: "R58-S-0126",
    oldItemId: "R58-EL-050",
    itemName: "Socket 6A",
    openingQuantity: 49,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 127,
    stockId: "R58-S-0127",
    oldItemId: "R58-EL-051",
    itemName: "Switch 06Amp",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 128,
    stockId: "R58-S-0128",
    oldItemId: "R58-EL-052",
    itemName: "Switch 16Amp",
    openingQuantity: 80,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 129,
    stockId: "R58-S-0129",
    oldItemId: "R58-EL-053",
    itemName: "Junction Box PVC 2 hole",
    openingQuantity: 7,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 130,
    stockId: "R58-S-0130",
    oldItemId: "R58-EL-054",
    itemName: "Junction Box PVC 3 hole",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 131,
    stockId: "R58-S-0131",
    oldItemId: "R58-EL-055",
    itemName: "Combined Double 16A",
    openingQuantity: 17,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 132,
    stockId: "R58-S-0132",
    oldItemId: "R58-EL-056",
    itemName: "Bearing 6201-2Z",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 133,
    stockId: "R58-S-0133",
    oldItemId: "R58-EL-057",
    itemName: "Bearing 6202-2Z",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 134,
    stockId: "R58-S-0134",
    oldItemId: "R58-EL-058",
    itemName: "Bend 25mm PVC",
    openingQuantity: 45,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 135,
    stockId: "R58-S-0135",
    oldItemId: "R58-EL-059",
    itemName: "Burfee Holder",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 136,
    stockId: "R58-S-0136",
    oldItemId: "R58-EL-060",
    itemName: "Cable 120mm 3.5core",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 137,
    stockId: "R58-S-0137",
    oldItemId: "R58-EL-061",
    itemName: "Cable 25mm 4core",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 138,
    stockId: "R58-S-0138",
    oldItemId: "R58-EL-062",
    itemName: "Cooler Jali Big",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 139,
    stockId: "R58-S-0139",
    oldItemId: "R58-EL-063",
    itemName: "Cooler Jali Small",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 140,
    stockId: "R58-S-0140",
    oldItemId: "R58-EL-064",
    itemName: "Cooler Pad Big",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 141,
    stockId: "R58-S-0141",
    oldItemId: "R58-EL-065",
    itemName: "Cooler Pad Small",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 142,
    stockId: "R58-S-0142",
    oldItemId: "R58-EL-066",
    itemName: "Cooler Pump Big",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 143,
    stockId: "R58-S-0143",
    oldItemId: "R58-EL-067",
    itemName: "Cooler Pump Small",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 144,
    stockId: "R58-S-0144",
    oldItemId: "R58-EL-068",
    itemName: "Exhaust Fan 150mm",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 145,
    stockId: "R58-S-0145",
    oldItemId: "R58-EL-069",
    itemName: "Exhaust Fan 18\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 146,
    stockId: "R58-S-0146",
    oldItemId: "R58-EL-070",
    itemName: "Exhaust Fan 200mm",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 147,
    stockId: "R58-S-0147",
    oldItemId: "R58-EL-071",
    itemName: "Exhaust Fan Blade 18\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 148,
    stockId: "R58-S-0148",
    oldItemId: "R58-EL-072",
    itemName: "Exhaust Fan Blade 24\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 149,
    stockId: "R58-S-0149",
    oldItemId: "R58-EL-073",
    itemName: "Fall Ceiling Light Cover",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 150,
    stockId: "R58-S-0150",
    oldItemId: "R58-EL-074",
    itemName: "Fan Blade Frata",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 151,
    stockId: "R58-S-0151",
    oldItemId: "R58-EL-075",
    itemName: "Fan_Wall_Type",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 152,
    stockId: "R58-S-0152",
    oldItemId: "R58-EL-076",
    itemName: "Fancy Light_Ceiling",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 153,
    stockId: "R58-S-0153",
    oldItemId: "R58-EL-077",
    itemName: "Fancy Light_Wall",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 154,
    stockId: "R58-S-0154",
    oldItemId: "R58-EL-078",
    itemName: "Flexible Pipe 20mm/ 3/4\" (heavy)",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 155,
    stockId: "R58-S-0155",
    oldItemId: "R58-EL-079",
    itemName: "Flexible Pipe 20mm/ 3/4\" (medium)",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 156,
    stockId: "R58-S-0156",
    oldItemId: "R58-EL-080",
    itemName: "Flexible Pipe 25mm/1\" (heavy)",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 157,
    stockId: "R58-S-0157",
    oldItemId: "R58-EL-081",
    itemName: "Flexible Pipe 25mm/1\" (medium)",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 158,
    stockId: "R58-S-0158",
    oldItemId: "R58-EL-082",
    itemName: "Geyser Heating Element Set",
    openingQuantity: 32,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 159,
    stockId: "R58-S-0159",
    oldItemId: "R58-EL-083",
    itemName: "LED Bulb 50W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 160,
    stockId: "R58-S-0160",
    oldItemId: "R58-EL-084",
    itemName: "LED Bulb Filament 6W w/w B-22",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 161,
    stockId: "R58-S-0161",
    oldItemId: "R58-EL-085",
    itemName: "LED Bulb Filament 6W w/w E-27",
    openingQuantity: 10,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 162,
    stockId: "R58-S-0162",
    oldItemId: "R58-EL-086",
    itemName: "LED Bulb Mirchi (Jhumar)",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 163,
    stockId: "R58-S-0163",
    oldItemId: "R58-EL-087",
    itemName: "LED Light Glass",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 164,
    stockId: "R58-S-0164",
    oldItemId: "R58-EL-088",
    itemName: "LED Panel Light 2X2 36W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 165,
    stockId: "R58-S-0165",
    oldItemId: "R58-EL-089",
    itemName: "LED Strip Flexble 5mtr",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 166,
    stockId: "R58-S-0166",
    oldItemId: "R58-EL-090",
    itemName: "LED Tubelight 05W 2ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 167,
    stockId: "R58-S-0167",
    oldItemId: "R58-EL-091",
    itemName: "LED Tubelight 10W 2ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 168,
    stockId: "R58-S-0168",
    oldItemId: "R58-EL-092",
    itemName: "LED Tubelight 20W 4ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 169,
    stockId: "R58-S-0169",
    oldItemId: "R58-EL-093",
    itemName: "LED Tubelight 32W 4ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 170,
    stockId: "R58-S-0170",
    oldItemId: "R58-EL-094",
    itemName: "LED Tubelight 36W 4ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 171,
    stockId: "R58-S-0171",
    oldItemId: "R58-EL-095",
    itemName: "LED Tubelight 40W 4ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 172,
    stockId: "R58-S-0172",
    oldItemId: "R58-EL-096",
    itemName: "Pipe PVC 25mm/1\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 173,
    stockId: "R58-S-0173",
    oldItemId: "R58-EL-097",
    itemName: "Pipe PVC 25mm/1\" Heavy",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 174,
    stockId: "R58-S-0174",
    oldItemId: "R58-EL-098",
    itemName: "Plaas",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 175,
    stockId: "R58-S-0175",
    oldItemId: "R58-EL-099",
    itemName: "Rachet Tool Kit",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 176,
    stockId: "R58-S-0176",
    oldItemId: "R58-EL-100",
    itemName: "Slim Panel Light 18W Round",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 177,
    stockId: "R58-S-0177",
    oldItemId: "R58-EL-101",
    itemName: "Slim Panel Light 22W Round",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 178,
    stockId: "R58-S-0178",
    oldItemId: "R58-EL-102",
    itemName: "Surface Light 03W Round W/W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 179,
    stockId: "R58-S-0179",
    oldItemId: "R58-EL-103",
    itemName: "Surface Light 12W Round",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 180,
    stockId: "R58-S-0180",
    oldItemId: "R58-EL-104",
    itemName: "Surface Light 15W Round W/W",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 181,
    stockId: "R58-S-0181",
    oldItemId: "R58-EL-105",
    itemName: "Surface Track 20W (Black)",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 182,
    stockId: "R58-S-0182",
    oldItemId: "R58-EL-106",
    itemName: "Surface Track 30W (White)",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 183,
    stockId: "R58-S-0183",
    oldItemId: "R58-EL-107",
    itemName: "Surface Track 7W (White)",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 184,
    stockId: "R58-S-0184",
    oldItemId: "R58-EL-108",
    itemName: "Top 2 pin",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 185,
    stockId: "R58-S-0185",
    oldItemId: "R58-EL-109",
    itemName: "Wire 1 mm",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 186,
    stockId: "R58-S-0186",
    oldItemId: "R58-EL-110",
    itemName: "Wire 1.5mm",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 187,
    stockId: "R58-S-0187",
    oldItemId: "R58-EL-111",
    itemName: "Wire 2.5mm",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 188,
    stockId: "R58-S-0188",
    oldItemId: "R58-EL-112",
    itemName: "Wire 3 Core 2.5mm",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 189,
    stockId: "R58-S-0189",
    oldItemId: "R58-EL-113",
    itemName: "Wire 4 mm",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 190,
    stockId: "R58-S-0190",
    oldItemId: "R58-EL-114",
    itemName: "Wire 6 mm",
    openingQuantity: 0,
    unit: "Meter",
    minimumStock: 0,
  },
  {
    sizeId: 191,
    stockId: "R58-S-0191",
    oldItemId: "R58-EL-015",
    itemName: "Combined Single 16A",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 192,
    stockId: "R58-S-0192",
    oldItemId: "R58-PB-077",
    itemName: "Ball Cock Brass ½\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 193,
    stockId: "R58-S-0193",
    oldItemId: "R58-PB-078",
    itemName: "Adapter GI 1¼\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 194,
    stockId: "R58-S-0194",
    oldItemId: "R58-PB-079",
    itemName: "Adapter GI 1½\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 195,
    stockId: "R58-S-0195",
    oldItemId: "R58-PB-080",
    itemName: "Ball Cock PVC ½\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 196,
    stockId: "R58-S-0196",
    oldItemId: "R58-PB-081",
    itemName: "Ball PVC ½\"X6\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 197,
    stockId: "R58-S-0197",
    oldItemId: "R58-PB-082",
    itemName: "Ball Valve 1½\" UPVC",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 198,
    stockId: "R58-S-0198",
    oldItemId: "R58-PB-083",
    itemName: "Ball Valve 2\" UPVC",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 199,
    stockId: "R58-S-0199",
    oldItemId: "R58-PB-084",
    itemName: "Bush CPVC 1\"X¾\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 200,
    stockId: "R58-S-0200",
    oldItemId: "R58-PB-085",
    itemName: "Cistern Handle",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 201,
    stockId: "R58-S-0201",
    oldItemId: "R58-PB-086",
    itemName: "Clamp PVC ¾\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 202,
    stockId: "R58-S-0202",
    oldItemId: "R58-PB-087",
    itemName: "Clamp PVC 1\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 203,
    stockId: "R58-S-0203",
    oldItemId: "R58-PB-088",
    itemName: "Clamp PVC 32mm Double",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 204,
    stockId: "R58-S-0204",
    oldItemId: "R58-PB-089",
    itemName: "Connection Pipe 18\" PVC",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 205,
    stockId: "R58-S-0205",
    oldItemId: "R58-PB-090",
    itemName: "Connection Pipe 24\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 206,
    stockId: "R58-S-0206",
    oldItemId: "R58-PB-091",
    itemName: "Drill Bit 6mm",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 207,
    stockId: "R58-S-0207",
    oldItemId: "R58-PB-092",
    itemName: "Elbow PVC 3\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 208,
    stockId: "R58-S-0208",
    oldItemId: "R58-PB-093",
    itemName: "Hex Nipple ½\" MS",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 209,
    stockId: "R58-S-0209",
    oldItemId: "R58-PB-094",
    itemName: "Keel 3\" MS",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 210,
    stockId: "R58-S-0210",
    oldItemId: "R58-PB-095",
    itemName: "Mirror",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 211,
    stockId: "R58-S-0211",
    oldItemId: "R58-PB-096",
    itemName: "MS Fastner 4X10mm",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 212,
    stockId: "R58-S-0212",
    oldItemId: "R58-PB-097",
    itemName: "Pipe CPVC ¾\" 10ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 213,
    stockId: "R58-S-0213",
    oldItemId: "R58-PB-098",
    itemName: "Pipe CPVC 1\" 10ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 214,
    stockId: "R58-S-0214",
    oldItemId: "R58-PB-099",
    itemName: "Pipe PVC 6\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 215,
    stockId: "R58-S-0215",
    oldItemId: "R58-PB-100",
    itemName: "Pipe UPVC ¾\" 10ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 216,
    stockId: "R58-S-0216",
    oldItemId: "R58-PB-101",
    itemName: "Pipe UPVC 1\" 10ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 217,
    stockId: "R58-S-0217",
    oldItemId: "R58-PB-102",
    itemName: "Pipe UPVC 1½\" 10ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 218,
    stockId: "R58-S-0218",
    oldItemId: "R58-PB-103",
    itemName: "Pipe UPVC 2\" 10ft",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 219,
    stockId: "R58-S-0219",
    oldItemId: "R58-PB-104",
    itemName: "Push Tooti SS",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 220,
    stockId: "R58-S-0220",
    oldItemId: "R58-PB-105",
    itemName: "PVC Cistren Washer ¾\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 221,
    stockId: "R58-S-0221",
    oldItemId: "R58-PB-106",
    itemName: "PVC Connection Washer",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 222,
    stockId: "R58-S-0222",
    oldItemId: "R58-PB-107",
    itemName: "Screw Driver",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 223,
    stockId: "R58-S-0223",
    oldItemId: "R58-PB-108",
    itemName: "Sink Jali",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 224,
    stockId: "R58-S-0224",
    oldItemId: "R58-PB-109",
    itemName: "Socket GI ½\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 225,
    stockId: "R58-S-0225",
    oldItemId: "R58-PB-110",
    itemName: "Tail Flange PVC 6\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 226,
    stockId: "R58-S-0226",
    oldItemId: "R58-PB-111",
    itemName: "Tejab",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 227,
    stockId: "R58-S-0227",
    oldItemId: "R58-PB-112",
    itemName: "Tota Plaas",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 228,
    stockId: "R58-S-0228",
    oldItemId: "R58-PB-113",
    itemName: "Waste Pipe",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 229,
    stockId: "R58-S-0229",
    oldItemId: "R58-PB-114",
    itemName: "Union GI 1½\" (heavy)",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 230,
    stockId: "R58-S-0230",
    oldItemId: "R58-PB-115",
    itemName: "Ball Valve 1\" UPVC",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 231,
    stockId: "R58-S-0231",
    oldItemId: "R58-PB-116",
    itemName: "FTA UPVC 1\"X1\"",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 232,
    stockId: "R58-S-0232",
    oldItemId: "R58-PB-117",
    itemName: "FTA UPVC 1½\" Brass",
    openingQuantity: 5,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 233,
    stockId: "R58-S-0233",
    oldItemId: "R58-PB-118",
    itemName: "Solvent PVC 237ml",
    openingQuantity: 4,
    unit: "Bottle",
    minimumStock: 0,
  },
  {
    sizeId: 234,
    stockId: "R58-S-0234",
    oldItemId: "R58-EL-115",
    itemName: "LED Bulb 18w",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 235,
    stockId: "R58-S-0235",
    oldItemId: "R58-EL-116",
    itemName: "LED Bulb 9w_Churiwala",
    openingQuantity: 4,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 236,
    stockId: "R58-S-0236",
    oldItemId: "R58-EL-117",
    itemName: "Switch Blank",
    openingQuantity: 36,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 237,
    stockId: "R58-S-0237",
    oldItemId: "R58-EL-118",
    itemName: "TV Socket",
    openingQuantity: 14,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 238,
    stockId: "R58-S-0238",
    oldItemId: "R58-PB-119",
    itemName: "Nipple GI 1¼\"X3\"",
    openingQuantity: 0,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 239,
    stockId: "R58-S-0239",
    oldItemId: "R58-EL-119",
    itemName: "Clip 25mm",
    openingQuantity: 140,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 240,
    stockId: "R58-S-0240",
    oldItemId: "R58-EL-120",
    itemName: "Extension Board",
    openingQuantity: 2,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 241,
    stockId: "R58-S-0241",
    oldItemId: "R58-PB-120",
    itemName: "MTA UPVC 1\"x1\" SS",
    openingQuantity: 1,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 242,
    stockId: "R58-S-0242",
    oldItemId: "R58-EL-121",
    itemName: "Halogen 40W",
    openingQuantity: 18,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 243,
    stockId: "R58-S-0243",
    oldItemId: "R58-EL-122",
    itemName: "Mini Halogen",
    openingQuantity: 7,
    unit: "Pcs",
    minimumStock: 0,
  },
  {
    sizeId: 244,
    stockId: "R58-S-0244",
    oldItemId: "R58-EL-123",
    itemName: "Glass Sheet",
    openingQuantity: 3,
    unit: "Pcs",
    minimumStock: 0,
  },
];